import Head from "next/head";
import "../../../public/style.css";

export default function Archive() {
  return (
    <>
      <Head>
        <title>archive</title>
      </Head>
      <div>
        <p>
          flocrivello.com/changing-my-mind-on-remote-about-being-in-san-francisco
        </p>
        <p>blog.mattneary.com/worse-is-better</p>
        <p>rfc-editor.org/rfc/rfc1178</p>
        <p>
          inc.com/jason-aten/tech-companies-keep-falling-for-forever-fallacy-why-smart-leaders-should-know-better.html
        </p>
        <p>
          slate.com/human-interest/2012/05/how-to-cook-onions-why-recipe-writers-lie-and-lie-about-how-long-they-take-to-caramelize.html
        </p>
        <p>
          careershifters.org/expert-advice/the-forever-fallacy-or-why-youre-probably-not-going-to-find-your-perfect-career-and
        </p>
        <p>edconway.substack.com/p/watching-paint-dry</p>
        <p>engineersneedart.com/blog/samestop/samestop.html</p>
        <p>write.as/synth-ruiner/the-low-tech-manifesto</p>
        <p>tinybird.info/reputation-laundering</p>
        <p>subpixel.space/entries/life-after-lifestyle</p>
        <p>
          colin-scott.github.io/personal_website/research/interactive_latency.html
        </p>
        <p>archive.ph/VIbMD</p>
        <p>bit.kevinslin.com/p/leveraging-gpt-4-to-automate-the</p>
        <p>reproof.app/blog/notes-apps-help-us-forget</p>
        <p>gaultier.github.io/blog/x11_x64.html</p>
        <p>ntietz.com/blog/ai-text-should-be-labeled</p>
        <p>how-i-experience-web-today.com</p>
        <p>
          web.archive.org/web/20210513043002/web.eecs.utk.edu/~azh/blog/cosine.html
        </p>
        <p>
          wsj.com/articles/west-coast-states-rode-the-tech-boom-now-they-face-higher-unemployment-falling-wages-83318105
        </p>
        <p>
          neptune.ai/blog/understanding-vectors-from-a-machine-learning-perspective
        </p>
        <p>quuxplusone.github.io/blog/2023/06/02/not-so-quick-pmr</p>
        <p>freshpaint.io/blog/github-copilot-and-the-methods-of-rationality</p>
        <p>iucompilercourse.github.io/tutorial-web-page</p>
        <p>jvns.ca/blog/2023/06/05/some-blogging-myths</p>
        <p>nskyc.com</p>
        <p>thezbook.com/code-first-vs-product-first</p>
        <p>notes.jordanscales.com/block-the-blue</p>
        <p>wy-lang.org</p>
        <p>mina-marketti.ocnk.net/product-list/206</p>
        <p>austinhenley.com/blog/makinggames.html</p>
        <p>dwheeler.com/essays/filenames-in-shell.html</p>
        <p>saurabhs.org/advanced-macos-commands</p>
        <p>neal.fun/password-game</p>
        <p>mowglii.com/itsycal/datetime.html</p>
        <p>cooklang.org</p>
        <p>washingtonpost.com/technology/2023/08/15/twitter-x-links-delayed</p>
        <p>
          wsj.com/articles/that-plum-job-listing-may-just-be-a-ghost-3aafc794
        </p>
        <p>motherfuckingwebsite.com</p>
        <p>code.golf</p>
        <p>blog.robertelder.org/how-to-make-a-cpu</p>
        <p>milan.cvitkovic.net/writing/things_youre_allowed_to_do</p>
        <p>jmmv.dev/2020/03/test-bracket.html</p>
        <p>mindingourway.com/obvious-advice</p>
        <p>
          programs.clearerthinking.org/what_is_your_time_really_worth_to_you.html
        </p>
        <p>
          johnsalvatier.org/blog/2017/reality-has-a-surprising-amount-of-detail
        </p>
        <p>scattered-thoughts.net/writing/there-are-no-strings-on-me</p>
        <p>danluu.com/why-benchmark</p>
        <p>
          quantamagazine.org/the-biggest-discoveries-in-computer-science-in-2023-20231220
        </p>
        <p>soggy.cat</p>
        <p>www.selfawaresoup.com/notes/2024/05/01/the-user-is-on-their-own/</p>
        <p>layoffs.fyi</p>
        <p>lastfun.site/intent</p>
        <p>gossipsweb.net/personal-websites</p>
        <p>jimmyhmiller.github.io/ugliest-beautiful-codebase</p>
        <p>thecut.com/2023/11/adulthood-is-a-mirage.html</p>
      </div>
    </>
  );
}
